name: Check Files

on: [push, pull_request]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: List workspace contents
      run: ls -R $GITHUB_WORKSPACE

    - name: Show file content
      run: cat ${GITHUB_WORKSPACE}/path/to/your/a.txt 
